### ISSUE TITLE
"Field 'getProjectsByUser' of extended 'Query' must hold a `@resolver` directive."

### ISSUE THREAD

**Issue by SmartDev0910** [grafbase/grafbase#424]
**Describe the bug**
When I implement to get data by user, I can't write query using grafbase.

**Comment by notrab** [comment]
Hey @SmartDev0910 

Grafbase automatically generates queries and mutations based on your `@model` types. You can use the `by` argument with those generated queries to fetch by the `id` or any other `@unique` field &mdash; [documentation](https://grafbase.com/docs/database/queries#fetch-by)

This means you can remove the following code from your `grafbase/schema.graphql`:

```graphql
extend type Query @resolver {
  getProjectsByUser(user: String!): [Project!]
}
```

You can also remove `id: ID! @unique` since that's a [system field](https://grafbase.com/docs/database/system-fields#id) automatically managed by Grafbase.

With these changes your final `grafbase/schema.graphql` should look like this:

```graphql
# grafbase/schema.graphql
type Project @model {
  title: String!
  description: String!
  userBy: String!
}
```

I'll go ahead and close the issue but feel free to reply if you have any further questions.

**Comment by SmartDev0910** [comment]
Hi @notrab 
Thanks for your reply.
I had already known grafbase will generate some queries automatically. But the queries just limited.
For example, when I set scheme @model, grafbase will generate `projectCreate`, `projectUpdate`, `projectDelete`.
And when I talk about @unique, I had already implemented `id: ID! @unique`, then the query will be only got data by id. But I wanted to get data by userBy, one of the field.

**Comment by notrab** [comment]
Hey @SmartDev0910 

You should add `@unique` to the `userBy` field to update the `by` query:

```graphql
type Project @model {
  title: String!
  description: String!
  userBy: String! @unique
}
```

**Comment by SmartDev0910** [comment]
Thanks for your reply.

```
type Project @model {
  id: String! @unique
  title: String!
  description: String!
  userBy: String! @unique
}
```

I wanted to do like the above. Is it possible?

**Comment by notrab** [comment]
@SmartDev0910 I'm not sure what you're asking for. That is the same. `id` is managed for you, so you don't need to add it to the `Project` type.
